# Numpy

## Array

In [1]:
import numpy as np

In [2]:
# Creating Array

arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.empty(3)

array([9.34609111e-307, 1.11259940e-306, 9.34598926e-307])

In [9]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.empty(2)

array([1.06220910e-187, 9.51078939e+256])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [16]:
# Add, Remove, Sort

In [17]:
arrayAwal = np.arange(1, 9)

In [18]:
arrayAwal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arrayBaru = np.append(arrayAwal, [1, 2, 3])
arrayBaru

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [21]:
np.delete(arrayBaru, 3)

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [26]:
np.delete(arrayBaru, (1, 5))

array([1, 3, 4, 5, 7, 8, 1, 2, 3])

In [27]:
# Shape and size

In [28]:
contohArray = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                       [[0, 1, 2, 3], [4, 5, 6, 7]],
                       [[0, 1, 2, 3], [4, 5, 6, 7]]])

In [29]:
contohArray

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [30]:
contohArray.ndim

3

In [31]:
contohArray.size

24

In [32]:
#output : size, ax vertical, ax horizontal
contohArray.shape

(3, 2, 4)

In [33]:
# Reshape

In [34]:
arr = np.arange(6)

arr

array([0, 1, 2, 3, 4, 5])

In [35]:
newArr = arr.reshape(3, 2)

newArr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
newArr.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [39]:
newArr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
# convert 1D to 2D

arr

array([0, 1, 2, 3, 4, 5])

In [41]:
newArr = arr[np.newaxis]

In [42]:
newArr.shape

(1, 6)

In [43]:
arr[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5]])

In [45]:
arr[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
arr

array([0, 1, 2, 3, 4, 5])

In [48]:
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [49]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [50]:
# Indexing and Slicing

In [51]:
data = np.array([1, 2, 3])

In [52]:
data

array([1, 2, 3])

In [53]:
print(data)

[1 2 3]


In [54]:
data[0]

1

In [55]:
data[-1]

3

In [56]:
data[:1]

array([1])

In [57]:
data[1:]

array([2, 3])

In [58]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a.shape

(3, 4)

In [60]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# creating array from existing data

In [63]:
arrayBaru

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [66]:
arrayBaru2 = arrayBaru[3:8]

arrayBaru2

array([4, 5, 6, 7, 8])

In [67]:
a_1 = np.array([[1, 1], [2, 2]])
a_2 = np.array([[3, 3], [4, 4]])

print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [68]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [69]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [71]:
arrayBaru

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [72]:
#shallow copy, hanya proyeksi
arrayBaru3= arrayBaru.view()

In [73]:
# pure copy, tidak terpengaruh perubahan array awal
arrayBaru4 = arrayBaru.copy()

In [74]:
print(arrayBaru3)
print(arrayBaru4)

[1 2 3 4 5 6 7 8 1 2 3]
[1 2 3 4 5 6 7 8 1 2 3]


In [75]:
# Basic array operations

In [76]:
data = np.array([1, 2])
ones = np.ones(2)

In [77]:
print(data)
print(ones)

[1 2]
[1. 1.]


In [78]:
data + ones

array([2., 3.])

In [79]:
data * ones

array([1., 2.])

In [80]:
arrayBaru.sum()

42

In [81]:
a_1

array([[1, 1],
       [2, 2]])

In [82]:
a_1.sum()

6

In [83]:
a_1.sum(axis=1)

array([2, 4])

In [84]:
a_1.sum(axis=0)

array([3, 3])

In [85]:
data * 4

array([4, 8])

In [86]:
arrayBaru.max()

8

In [87]:
a_1.max(axis=1)

array([1, 2])

In [88]:
a_1.max(axis=0)

array([2, 2])

## Matrices

In [89]:
# Creating Matrices

In [90]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [91]:
np.ones(3)

array([1., 1., 1.])

In [92]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [93]:
np.random.random((3,2))

array([[0.5913034 , 0.39227725],
       [0.42353082, 0.68467408],
       [0.46978757, 0.81147249]])

In [95]:
# Dot Product

In [96]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
a_2 = np.array([[7, 8], [9, 10], [11, 12]])

np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [98]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [99]:
data[1]

array([3, 4])

In [100]:
data[0, 1]

2

In [101]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [102]:
data[0:2, 1]

array([2, 4])

In [103]:
# Matrix Aggr

In [105]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
data.max()

6

In [107]:
# Transpose and Reshape

In [108]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [109]:
data.shape

(3, 2)

In [110]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
# N Dimensional Array

In [116]:
np.array([[[1, 2], [3, 4]],
         [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [117]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [118]:
arrflat = np.zeros((4, 3))

In [119]:
arrflat.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
a = np.ones(4)

In [121]:
a.T

array([1., 1., 1., 1.])

In [122]:
a.shape

(4,)

In [124]:
np.dot(a, a.T)

4.0

In [125]:
a = np.ones((5, 1))

In [126]:
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])