# Sesi 9

Descriptive Statistics

- To help summarizing data.
- measure of variability between mean, median, modus to represent the data
- dispersion : mean, range, standar deviation

In [2]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [3]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [5]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(z)

[ 8.   1.   2.5  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64


## Measure of Central Tendency

### Mean

In [7]:
sum(x) / len(x)

8.7

In [8]:
statistics.mean(x)

8.7

In [9]:
statistics.mean(x_with_nan)

nan

In [10]:
sum(x_with_nan) / len(x)

nan

In [11]:
np.mean(y)

8.7

In [12]:
np.mean(y_with_nan)

nan

In [13]:
np.nanmean(y_with_nan)

8.7

In [14]:
z.mean()

8.7

In [15]:
z_with_nan.mean()

8.7

In [23]:
np.average(x)

8.7

In [24]:
np.average(x_with_nan)

nan

## Weighted Mean

In [18]:
x

[8.0, 1, 2.5, 4, 28.0]

In [19]:
w = [0.1, 0.2, 0.3, 0.25, 0.15]

In [20]:
w = np.array(w)

In [21]:
np.average(y, weights = w)

6.95

In [22]:
np.average(z, weights = w)

6.95

## Harmonic Mean

In [26]:
statistics.harmonic_mean(x)

2.7613412228796843

In [27]:
scipy.stats.hmean(y)

2.7613412228796843

## Geometric Mean

In [29]:
scipy.stats.gmean(y)

4.67788567485604

## Median

In [31]:
x

[8.0, 1, 2.5, 4, 28.0]

In [36]:
m = x[:-1]
m

[8.0, 1, 2.5, 4]

In [37]:
statistics.median_low(m)

2.5

In [38]:
statistics.median_high(m)

4

In [39]:
statistics.median(m)

3.25

In [40]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [41]:
statistics.median_low(x_with_nan)

4

In [42]:
np.median(y)

4.0

## Mode

In [44]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [45]:
statistics.mode(u)

2

In [49]:
u, v = np.array(u), np.array(v)
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [52]:
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

In [50]:
u, v = pd.Series(u), pd.Series(v)

u.mode()

0    2
dtype: int32

In [51]:
v.mode()

0    12
1    15
dtype: int32

## Measures of Variability

### Variance

In [57]:
x

[8.0, 1, 2.5, 4, 28.0]

In [55]:
statistics.variance(x)

123.2

In [56]:
np.var(y, ddof=1)

123.19999999999999

In [58]:
z.var(ddof=1)

123.19999999999999

### Standard Deviation

In [60]:
statistics.stdev(x)

11.099549540409287

In [61]:
np.std(y, ddof=1)

11.099549540409285

In [62]:
z.std(ddof=1)

11.099549540409285

### Skewness

In [64]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [65]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [66]:
z.skew()

1.9470432273905924

### Percentiles

In [73]:
x = [41.0, -5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0,25.8]

In [69]:
statistics.quantiles(x, n=2)

[8.0]

In [74]:
y = np.array(x)
y

array([41. , -5. , -1.1,  0.1,  2. ,  8. , 12.8, 21. , 25.8])

In [75]:
np.percentile(y, 5)

-3.44

In [76]:
np.percentile(y, 50)

8.0

In [77]:
np.percentile(y, 95)

34.919999999999995

In [78]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [79]:
np.quantile(y, 0.5)

8.0

In [80]:
z= pd.Series(y)

### Ranges

In [82]:
np.ptp(y)

46.0

In [83]:
np.ptp(z)

46.0

### Summary of Descriptive Stats

In [85]:
scipy.stats.describe(y, ddof=1, bias=False)

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [86]:
z.describe()

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

## Measure of Correlation

In [88]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

### Covariance

In [91]:
np.cov(x_, y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

### Correlation Coefficient

In [93]:
scipy.stats.pearsonr(x_, y_)

(0.8619500056316061, 5.122760847201135e-07)

In [94]:
np.corrcoef(x_, y_)

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])